language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
    allow_failures:
    - rust: nightly
    fast_finish: true
script:
    - export XDG_CURRENT_DESKTOP Dunno
    - cargo build --verbose --all --release
    - cargo test --verbose --all --release